### ISSUE TITLE
[Feature]: Completely reload all of LunarVim config as if Neovim restarted

### ISSUE THREAD

**Issue by pidgeon777** [ChristianChiarulli/nvcode#1230]
### Feature motivation

There is no way to completely reload all of the LunarVim config without restarting Neovim, sequentially (sequence is important).

For example, if a new plugin is activated, then after the `PackerCompile` it is necessary to restart Neovim to see the effects, finally proceeding with `PackerInstall`.

More in general, what I'm looking for is a way to completely reset and refresh LunarVim settings as done during its startup.

### Describe the expected solution

Maybe something like this could work?:

Have a `util.lua` file that defines the following:

````lua
_G.load = function(file)
    require("plenary.reload").reload_module(file, true)
    return require(file)
end
````

Then, instead of writing `require(...)`, write `load(...)` and the only file to require is `util.lua`, which is also the first one.

Then have the following mapping defined:

````lua
util.nnoremap("<leader>sv", "<cmd>luafile $MYVIMRC<CR>")
````

Which reloads the whole config.

https://stackoverflow.com/questions/68415300/how-can-i-reload-my-neovim-config-written-in-lua-with-a-shortcut

**Comment by kylo252** [comment]
I've definitely thought about this, but still didn't see a full example of what's required. 
I've messed around a bit with `:Telescope reloader` but it appears to detect modules/packages instead of files. 

![image](https://user-images.githubusercontent.com/59826753/128367949-e6439467-6570-412b-9db4-4ff8d23e1b07.png)

So I'm not sure how to work with that.

**Comment by ahmedkhalf** [comment]
#1397, could close this issue

**Comment by githorse** [comment]
How was this resolved? If I make edits to my LunarVim config in one instance of Vim, is there a command I can re-run in another instance to reload it (ideally without losing all my open buffers, etc.)?
