### ISSUE TITLE
New Plug-in Install Method and Linters/Formatters

### ISSUE THREAD

**Issue by cenk1cenk2** [ChristianChiarulli/nvcode#129]
Hello @ChristianChiarulli,

Initially thank you for your all contribution to the Neovim crowd, preparing educational videos about the neovim configuration as well as maintaining this repository, where everyone's requests and use cases differ from each other. 

I have got some contribution ideas, if you approve of them:
- An installation script for all the language servers where you can see [here](https://github.com/cenk1cenk2/nvim/blob/edf44e41bafa891bc1edd368d97225951189004c/utils/install-lsp.sh). This takes a similar approach to [vim-lsp-settings](https://github.com/mattn/vim-lsp-settings), where you can install node, python, golang, binary or vscode extensions locally in a folder instead of globally. So it is easily reproducable across multiple machines. This only requires to set the binary paths for each language server since they are not accessible globally.
- Drop custom sumneko-lua-extension build process and use the one bundled with the VSCode plugin. This simplifies the installation and configuration process quite at a bit. You can see the lua [here](https://github.com/cenk1cenk2/nvim/blob/62052d5db16341aef54eb1de9958914df93c8307/lua/lsp/lua.lua). The extension gets installed with the script so not much of building anything yourself.
- You mentioned your EFM configuration on the Youtube talk, but I wanted some more with Eslint and Tailwind, so there is a way to include them as language servers, and this makes eslint code actions enabled as well, since I am so used to them sometimes adding eslint-ignore lines. Since you do JavaScript/Typescript as well maybe that can be included as well. You can see the eslint configuration [here](https://github.com/cenk1cenk2/nvim/blob/62052d5db16341aef54eb1de9958914df93c8307/lua/lsp/eslint.lua).

I would love to open up a merge request for the issues discussed and if you find them worthy. My only problem is I already forked your repo, I have to find a way to re-fork it since it is much diverged :D.

Again, sincerely thank you for going in and addressing everyone's issues, while creating good quality content whether it is blog or on Youtube.

**Comment by ChristianChiarulli** [comment]
Thank you for the the feedback. I will tackle this issue once the install script is handled.
