### ISSUE TITLE
nv wiith lua doesn't work on MXLinux

### ISSUE THREAD

**Issue by smikeblog** [ChristianChiarulli/nvcode#135]
E5113: Error while calling lua chunk: /home/sm/.config/nvcode/init.lua:2: module 'plugins' not found:

Smw I've red that lua does not add locations to PATH/ It was about packer and ~/.local/share/nvim/**/opt/    folder.

**Comment by smikeblog** [comment]
packer will put plugins here ~/.local/**/site/pack/packer/start/  and this folder is used with all nvim as default. As a result other nvim will source packages from NVCode :-1:

**Comment by ChristianChiarulli** [comment]
Thanks for testing this out

Do you think they should they be in opt?

**Comment by smikeblog** [comment]
Yes! I use an old computer and have 3 vim/nvim configs/ Basic(vim), as text editor(nvim) and as an IDE(for programming languages) If I put plugins in start dir all nvim configs load them and where plugins are not configured plugins doesn't work correctly or doesn't work at all.

**Comment by ChristianChiarulli** [comment]
ok I will move the auto install to opt. The reason I used start was because I kept getting a prompt from packer when using opt during sync.

**Comment by smikeblog** [comment]
OK!

**Comment by batusai513** [comment]
I just found the same error on MacOS 10.15:
```E5113: Error while calling lua chunk: /Users/richard.roncancio/.config/nvcode/init.lua:4: module 'plugins' not found:
        no field package.preload['plugins']
        no file './lua/plugins.lua'
        no file './plugins.lua'
        no file '/Users/richard.roncancio/neovim/.deps/usr/share/luajit-2.1.0-beta3/plugins.lua'
        no file '/usr/local/share/lua/5.1/plugins.lua'
        no file '/usr/local/share/lua/5.1/plugins/init.lua'
        no file '/Users/richard.roncancio/neovim/.deps/usr/share/lua/5.1/plugins.lua'
        no file '/Users/richard.roncancio/neovim/.deps/usr/share/lua/5.1/plugins/init.lua'
        no file './plugins.so'
        no file '/usr/local/lib/lua/5.1/plugins.so'
        no file '/Users/richard.roncancio/neovim/.deps/usr/lib/lua/5.1/plugins.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'```

**Comment by smikeblog** [comment]
//I just found the same error on MacOS 10.15://
I think ChristianChiarulli  doesn't have error becase he has ~/.config/nvim/  alongside with proper settings. and ../plugins  module it seems to me his config takers from /.config/nvim/lua/ dir/

**Comment by fanmih** [comment]
I get the same error here: `Error E5113: Error while calling lua chunk: /Users/***/.config/nvcode/init.lua:5: module 'plugins' not found.`

OS: MacOS
Neo Vim version:
```
NVIM v0.5.0-dev+nightly-88-gc29494b71
Build type: Release
LuaJIT 2.1.0-beta3
```

`plugins.lua` exists on `/Users/***/.config/nvcode/lua` directory.
For reasons unknown to me this directory is not read when I start the `nv` executable.

if I am inside the `/Users/***/.config/nvcode/lua` directory and I start `nv` I get the error:
`Error E5113: Error while calling lua chunk: ./colorscheme.lua:1: Vim(colorscheme):E185: Cannot find color scheme 'nvcode'`

Any ideas?
Do we have to include a directory in our `$PATH`?

**Comment by smikeblog** [comment]
I mentioned the reason was  - because lua does not set path as vimscript does. Think how to make  vimscript :
set rtp+=~/.config/nvi... 
in lua code and you'll solve the problem. I'm using vim-plug which set the path to plugins ...

**Comment by ShivamJoker** [comment]
Same issue `Error while calling lua chunk`

**Comment by christiaan-janssen** [comment]
I have the same problem on lubuntu

```
E5113: Error while calling lua chunk: /home/***/.config/nvcode/init.lua:5: module 'plugins' not found:
        no field package.preload['plugins']
        no file './plugins.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/plugins.lua'
        no file '/usr/local/share/lua/5.1/plugins.lua'
        no file '/usr/local/share/lua/5.1/plugins/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/plugins.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/plugins/init.lua'
        no file './plugins.so'
        no file '/usr/local/lib/lua/5.1/plugins.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/plugins.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

os:
```
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```
nvim:
```
nvim --version
NVIM v0.5.0-dev+1152-gf5daf55c1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
os:

**Comment by fanmih** [comment]
Hello @smikeblog ,
I cloned your vim repo and I get similar mistakes
I run: `nvim -u ~/.config/nvim-lua/init.vim`
and get:
```
Error detected while processing /Users/zz/.config/nvim-lua/init.vim:
line   10:
E5108: Error executing lua [string ":lua"]:1: module 'init' not found:
        no field package.preload['init']
        no file './init.lua'
```
I do not know how to configure lua to search other directories for modules.

I tried `luarocks path` and I get:
```
export LUA_PATH='/usr/local/Cellar/luarocks/3.5.0/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua'
```
`nvcode` and subdirectories are not in the LUA_PATH.

Is it LUA_PATH that we have to change?

I do not know. No experience from `lua` programming.
What do you think?

**Comment by smikeblog** [comment]
> Hello @smikeblog ,
> I cloned your vim repo and I get similar mistakes
> I run: `nvim -u ~/.config/nvim-lua/init.vim`
> and get:
> 
> ```
> Error detected while processing /Users/zz/.config/nvim-lua/init.vim:
> line   10:
> E5108: Error executing lua [string ":lua"]:1: module 'init' not found:
>         no field package.preload['init']
>         no file './init.lua'
> ```
OK! it is natural because repo is as example and path is 
```
set rtp+=~/.config/nvimLua
```
i.e. repo is cloned to ~/.config/nvimLua
> 
> I do not know how to configure lua to search other directories for modules.
> 
> I tried `luarocks path` and I get:
> 
> ```
> export LUA_PATH='/usr/local/Cellar/luarocks/3.5.0/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua'
> ```
> 
> `nvcode` and subdirectories are not in the LUA_PATH.
> 

> Is it LUA_PATH that we have to change?
> 
> I do not know. No experience from `lua` programming.
> What do you think?
neovim/vim has runtimepath
help for path is in neovim ( :help runtimrpath )
this is the past for vim/neovim - not lua path which is for programming in lua

**Comment by batusai513** [comment]
I've added a PR that fixes the installation and first run: https://github.com/ChristianChiarulli/nvcode/pull/138

**Comment by smikeblog** [comment]
> I've added a PR that fixes the installation and first run: #138

Are you sure that this is solution:
```
vim.cmd('source ~/.config/nvim/lua/nv-vscode/init.vim')
```
and installation is cloned to 
```
$HOME/.config/nvcode
```
The Question is : Which one is your nvim folder nvcode or nvim 'cause you use both?

**Comment by batusai513** [comment]
@smikeblog I've tested a clean install with this branch and removed the nvim folder from .config, it installs and run

**Comment by smikeblog** [comment]
> @smikeblog I've tested a clean install with this branch and removed the nvim folder from .config, it installs and run

To make a clean install rename the standart runtome start dir
```
$HOME/.local/share/nvim/site/pack/packer/start/ 
```
All packages from this dir neovim load at start. and try to install again. 
It seems to me that it will nor work. 
Or simply move all files from start dor to opt dir   - i.e. 
```
.../packer/start  -> .../packer/opt  
``
/packer/opt/* dir is for lazy loaded  packages

**Comment by smikeblog** [comment]
> Thanks for testing this out
> 
> Do you think they should they be in opt?

My approach to vim/nvim configs is the same as here  https://github.com/farazdagi/vim-go-ide

**Comment by christiaan-janssen** [comment]
If I apply the change from #138 to a new install, and run :PackInstall it works for me. After install I get an error about missing treesitter, but nvcode is usable.

**Comment by smikeblog** [comment]
> If I apply the change from #138 to a new install, and run :PackInstall it works for me. After install I get an error about missing treesitter, but nvcode is usable.

Neovim has default runtimepath  and one dir in this path is 
```
~/.local/share/nvim/site/pack/*/
```
and packages in dirs
```
~/.local/share/nvim/site/pack/*/start/
```
are loaded automatically
and other subdirs  opt, syntax ... MUST be loaded to work i.e packadd + package name as help of the embedded package manager suggests
And finally when you delete ~/.config/nvim directory packages on the ~/.local/share/nvim/site/.../start/ derectory still there and you will not have errors.

**Comment by ChristianChiarulli** [comment]
This issue will be the next one I tackle the efm langserver. Thank you for all of the information.

**Comment by ChristianChiarulli** [comment]
Also I would like to support both the `nvim` dir and the `nvcode` dir
