### ISSUE TITLE
You have to be careful when configuring options in Lua.

### ISSUE THREAD

**Issue by mfiano** [ChristianChiarulli/nvcode#136]
The following is not setting the default as you might expect. You need to use `vim.bo` to set the default for that, since this is a buffer-local option. I haven't looked closely at the other options yet.

https://github.com/ChristianChiarulli/nvcode/blob/c9a5ddf161bfd9fddda037bd54453f8bcd7d0c18/lua/settings.lua#L18

PS Thank you for your stream. It has motivated me to switch to an all-Lua config.

**Comment by ChristianChiarulli** [comment]
Thanks for the advice. I'm still getting used to all of this Lua stuff myself, I'll have to go through all of these options closer soon too. Glad you enjoyed the stream.

**Comment by mfiano** [comment]
autoindent and fileencoding too

BTW, a lot of your options are set the neovim defaults, so you can get rid of them to make your config easier to maintain.

**Comment by ChristianChiarulli** [comment]
That's another thing I need to read over is the new sane defaults. From neovim. These were all basically set years ago when I was using vanilla vim.

**Comment by ChristianChiarulli** [comment]
All defaults should be removed now.

**Comment by GaetanLepage** [comment]
I noticed a strange behaviours with certain buffer options such as `smartindent`, `tabstop` and others.
This seems to be linked to this issue: https://github.com/neovim/neovim/issues/12978

Did some of you notice that ?
