### ISSUE TITLE
Lua autoformat as you show in video doesn't work.

### ISSUE THREAD

**Issue by hrqmonteiro** [ChristianChiarulli/nvcode#140]
I am trying to set the lua autoformat when saving, as you show [https://lbry.tv/@chrisatmachine:f/neovim-as-a-lua-ide-(autocomplete,:0](here).

I did it all right, i already had LSP configures, installed the efm-language-server, put it on my $PATH and so on.

But the commend you mention: `lua vim.lsp.buf.formatting()`

Gives me this error: 

![2021-03-16_23-25](https://user-images.githubusercontent.com/17055027/111405300-00750580-86af-11eb-88f2-65e005a17056.png)

And of course, if i try to put in the autocmd for when i save it, it does nothing.

**Comment by ChristianChiarulli** [comment]
you probably don't have it attached. run :LspInfo. You need a .git in the root of the repo.

**Comment by hrqmonteiro** [comment]
`:LspInfo`:

![2021-03-17_08-58](https://user-images.githubusercontent.com/17055027/111464037-0abef000-86ff-11eb-933d-b948d7f9c5ff.png)

I actually have a .git in the directory, cause my nvim dotfiles are on github.

**Comment by ChristianChiarulli** [comment]
I think you're right, try this:

```require"lspconfig".efm.setup {
    init_options = {documentFormatting = true},
    filetypes = {"lua"},
    settings = {
        rootMarkers = {".git/"},
        languages = {
            lua = {
                {
                    formatCommand = "lua-format -i --no-keep-simple-function-one-line --column-limit=100",
                    formatStdin = true
                }
            }
        }
    }
}
```

**Comment by thepenguinthatwants** [comment]
Hi,

I also tried to get the lua autoformat working.

In the  lua-ls.lua file
There doesn't seem to have a working example of having 

`autocmd BufWritePre *.lua lua vim.lsp.buf.formatting_sync(nil, 100)`

In lua format


`: lua vim.lsp.buf.formatting()` works tho but manually calling it feels annoying.


```
function nv_utils.formatting()
    vim.lsp.buf.formatting()
end

function nv_utils.formatting_sync()
    vim.lsp.buf.formatting_sync()
end
```

Should these cause the automatic formatting? Didn't seem to have any effects.

**Comment by ChristianChiarulli** [comment]
In my config you can call `:LspFormat`. Also look under nv-utils and you can add the autoformat commands there.

**Comment by ChristianChiarulli** [comment]
Also formatting should be configured in the efm server
