### ISSUE TITLE
[Bug]: Mapping <S-h> and <S-l> in barbar overrides default scrolling behaviour

### ISSUE THREAD

**Issue by andreacfromtheapp** [ChristianChiarulli/nvcode#1414]
### Problem description

these mappings: https://github.com/LunarVim/LunarVim/blob/rolling/lua/core/bufferline.lua#L7-L12
are overriding default scrolling behaviour in (n)vim. I use them frequently to jump around in code and there's no way to disable them. please consider other mappings or add an option to not set them by default. (unsetting the mappings doesn't seem to work either).

### LunarVim version

latest master

### Neovim version (>= 0.5)

nvim --version NVIM v0.5.0 Build type: Release LuaJIT 2.1.0-beta3

### Relevant log output

```shell
N/A
```

### Screenshots

N/A

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by eperfect** [comment]
> you can disable them using
> 
> ```lua
> lvim.keys.normal_mode["<S-l>"] = nil
> lvim.keys.normal_mode["<S-h>"] = nil
> ```
> 
> and map
> 
> ```viml
> :BufferNext
> ```
> 
> and
> 
> ```viml
> :BufferPrevious
> ```
> 
> to other keys
> 
> for example
> 
> ```lua
> lvim.keys.normal_mode["<S-l>"] = nil
> lvim.keys.normal_mode["]b"] = "<Cmd>BufferNext<CR>"
> ```

@abzcoding I changed my config like this, but it didn't work for me.
Here is my config:
 ```lua
lvim.keys.normal_mode["<s-h>"] = nil
lvim.keys.normal_mode["<s-l>"] = nil
lvim.keys.normal_mode["<c-j>"] = "<cmd>bufferprevious<cr>"
lvim.keys.normal_mode["<c-k>"] = "<cmd>buffernext<cr>"
 ```
......
Then I reload setting and check lvim keybindings use <leader>Lk, it's still there

 ```lua
normal_mode = {
 ....
    ["<C-j>"] = "<Cmd>BufferPrevious<CR>",
    ["<C-k>"] = "<Cmd>BufferNext<CR>",
    ["<C-l>"] = "<C-w>l",
    ["<C-q>"] = ":call QuickFixToggle()<CR>",
    ["<C-s>"] = "<Cmd>w<cr>",
    ["<S-h>"] = ":BufferPrevious<CR>",
    ["<S-l>"] = ":BufferNext<CR>",
    ["<S-x>"] = "<Cmd>BufferClose<CR>",
......
 ```
So how can I fix it? because I really need the default method of <S-h><S-l>, thank you very much.

**Comment by gacallea** [comment]
@eperfect S is capital for Shift. no s for s. same for C.

```
lvim.keys.normal_mode["<S-h>"] = nil
lvim.keys.normal_mode["<S-l>"] = nil
lvim.keys.normal_mode["<C-j>"] = "<cmd>bufferprevious<cr>"
lvim.keys.normal_mode["<C-k>"] = "<cmd>buffernext<cr>"
```

**Comment by eperfect** [comment]
> @eperfect S is capital for Shift. no s for s. same for C.
> 
> ```
> lvim.keys.normal_mode["<S-h>"] = nil
> lvim.keys.normal_mode["<S-l>"] = nil
> lvim.keys.normal_mode["<C-j>"] = "<cmd>bufferprevious<cr>"
> lvim.keys.normal_mode["<C-k>"] = "<cmd>buffernext<cr>"
> ```

Change to uppercase doesn't work too.

![image](https://user-images.githubusercontent.com/1331663/141775785-ab76398a-d9d7-40b1-b75c-486eb59cea12.png)
![image](https://user-images.githubusercontent.com/1331663/141775833-191047a2-82dd-4f44-bcd5-2480c40fbede.png)

**Comment by abzcoding** [comment]
instead of nil can you try setting them to false?
```lua
lvim.keys.normal_mode["<S-h>"] = false
lvim.keys.normal_mode["<S-l>"] = false
lvim.keys.normal_mode["<C-j>"] = "<cmd>bufferprevious<cr>"
lvim.keys.normal_mode["<C-k>"] = "<cmd>buffernext<cr>"
```

**Comment by eperfect** [comment]
> ```lua
> false
> ```

It works, thanks very much, also for awesome LunarVim.
