### ISSUE TITLE
Nvim install script "PackSync" command, wrong invoke

### ISSUE THREAD

**Issue by joaop-oliveira1** [ChristianChiarulli/nvcode#144]
This command insinde the `cloneconfig() ` function call has the wrong invocation command, i think the right one is `PackerSync` 
and its causing a silent crash in the terminal session...

`  nvim --headless +PackSync +qall > /dev/null 2>&1`

I don't know if it was information enough, in any case just mention me and I will be glad to provide more info!!!

Also great job in this config man!! I love it!

**Comment by ChristianChiarulli** [comment]
Thanks! I will get back to this script probably after today's stream.

**Comment by mohammedzeglam-pg** [comment]
> Thanks! I will get back to this script probably after today's stream.

local packer = nil
local function init()
  if packer == nil then
    packer = require('packer')
    packer.init({disable_commands = true})
  end

  local use = packer.use
  packer.reset()

  --Packer with optional plugin
  use {'wbthomason/packer.nvim', opt = true}

  --LSP
  use 'neovim/nvim-lspconfig'
  use 'glepnir/lspsaga.nvim'
  use 'onsails/lspkind-nvim'
  use 'kosayoda/nvim-lightbulb'
  --Icons
  use 'kyazdani42/nvim-web-devicons'
  use 'ryanoasis/vim-devicons'
  -- Treesitter
  use {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'}
  use 'nvim-treesitter/playground'
  use 'p00f/nvim-ts-rainbow'
  --Explorer
  use 'kyazdani42/nvim-tree.lua'

  -- General Plugins
  use 'windwp/nvim-autopairs'
  use 'akinsho/nvim-bufferline.lua'
  use '907th/vim-auto-save'
  -- Autocomplete
  use 'hrsh7th/nvim-compe'
  use 'hrsh7th/vim-vsnip'
  use 'hrsh7th/vim-vsnip-integ'
  use 'honza/vim-snippets'

  -- Telescope
  use 'nvim-lua/popup.nvim'
  use 'nvim-lua/plenary.nvim'
  use 'nvim-telescope/telescope.nvim'
  use 'nvim-telescope/telescope-media-files.nvim'
  --Formatter
  use 'sbdchd/neoformat'

  --Color
  use 'chriskempson/base16-vim'
  -- Status Line and Bufferline
  use 'glepnir/galaxyline.nvim'
  -- use {'akinsho/nvim-bufferline.lua', requires = 'kyazdani42/nvim-web-devicons'}
--  use 'romgrk/barbar.nvim'
    -- Git
    use 'TimUntersberger/neogit'
    use {'lewis6991/gitsigns.nvim', requires = {'nvim-lua/plenary.nvim'}}
    use 'f-person/git-blame.nvim'
    use 'tpope/vim-fugitive'
    use 'tpope/vim-rhubarb'

    -- Easily Create Gists
    use 'mattn/vim-gist'
    use 'mattn/webapi-vim'

    -- General Plugins
    use 'windwp/nvim-autopairs'
    use 'kevinhwang91/nvim-bqf'
    use 'unblevable/quick-scope'
    use 'airblade/vim-rooter'
    use 'kevinhwang91/rnvimr'
    use 'mhinz/vim-startify'
    use 'metakirby5/codi.vim'
    use 'psliwka/vim-smoothie'
    use {'iamcco/markdown-preview.nvim', run = 'cd app && npm install'}
    use 'moll/vim-bbye'
    use 'turbio/bracey.vim'
    use 'AndrewRadev/tagalong.vim'
    use 'alvan/vim-closetag'
    use 'liuchengxu/vim-which-key'
    use 'voldikss/vim-floaterm'
    use 'liuchengxu/vista.vim'
    use 'terrortylor/nvim-comment'
    use 'bfredl/nvim-miniyank'
    use 'junegunn/goyo.vim'
    use 'andymass/vim-matchup'
    use 'phaazon/hop.nvim'
    use 'gennaro-tedesco/nvim-jqx'
    use 'Yggdroot/indentLine'
		use 'tpope/vim-sleuth'
end
local plugins = setmetatable({}, {
 __index = function(_, key)
    init()
    return packer[key]
  end
})

return plugins
vim.cmd [[command! PackerInstall packadd packer.nvim | lua require('plugin').install()]]
vim.cmd [[command! PackerUpdate packadd packer.nvim | lua require('plugin').update()]]
vim.cmd [[command! PackerSync packadd packer.nvim | lua require('plugin').sync()]]
vim.cmd [[command! PackerClean packadd packer.nvim | lua require('plugin').clean()]]
vim.cmd [[command! PackerCompile packadd packer.nvim | lua require('plugin').compile()]]

**Comment by mohammedzeglam-pg** [comment]
> Thanks! I will get back to this script probably after today's stream.
use this it will fix your clean problem with packer and it will not quit vim when add new plugins
