### ISSUE TITLE
diagnostics

### ISSUE THREAD

**Issue by mybigman** [ChristianChiarulli/nvcode#153]
hey mate what plugin or piece of code in your config shows the diagnostic error?

<img width="350" alt="Screen Shot 2021-03-22 at 3 55 00 pm" src="https://user-images.githubusercontent.com/1289916/111942337-32f78600-8b27-11eb-8fbc-a7a666509a0f.png">

keep up the awesome work

**Comment by ChristianChiarulli** [comment]
you will need to look under `lua/lsp` there are a bunch of configured lang servers there. Seems like you have diagnostics showing tho no?

**Comment by mybigman** [comment]
thats your dot files thats working :)

mine has the LSP working but i dont get any form of diagnostics hence is it something specific i have to install or enable :/

**Comment by mybigman** [comment]
sorted... it needed to have a composer.json in the root
