### ISSUE TITLE
nv command does not open specified file

### ISSUE THREAD

**Issue by en1tan** [ChristianChiarulli/nvcode#155]
trying to use `nv somefile.txt` does not open the specified file, rather it opens the folder

**Comment by mjcc30** [comment]
hello it's because the nv command in ".config/nvcode/utils/bin"
refer to "nvim -u ~/.config/nvcode/init.lua"
if you add $1 it might work
like "nvim -u ~/.config/nvcode/init.lua $1" an do : "nv init.lua"

**Comment by en1tan** [comment]
thank you, works
