### ISSUE TITLE
javascript server is using efm not tsserver

### ISSUE THREAD

**Issue by wuhanhui** [ChristianChiarulli/nvcode#159]
I install tsserver with lsp but I found that when I open a js file it will use efm as the default server. How can I change it to tsserver while keeping efm as a lint tool.
![image](https://user-images.githubusercontent.com/9048191/112282850-75a19580-8cc2-11eb-99cd-edbe8360bd57.png)

**Comment by ChristianChiarulli** [comment]
try opening with package.json at the root.

**Comment by wuhanhui** [comment]
![image](https://user-images.githubusercontent.com/9048191/112406380-ff974000-8d4e-11eb-85e2-bd6dec46cb56.png)
only efm work

**Comment by chaeing** [comment]
Temporarily got it working by removing the following code in /lua/lsp/js-ts-ls.lua

cmd = {DATA_PATH .. "/lspinstall/typescript/node_modules/.bin/typescript-language-server", "--stdio"},

which was added in 7367ca68

**Comment by ChristianChiarulli** [comment]
oh, yea, you need to install typescript with LspInstall typescript now

**Comment by ChristianChiarulli** [comment]
I'm slowly transitioning to that helper

**Comment by wuhanhui** [comment]
> Temporarily got it working by removing the following line in /lua/lsp/js-ts-ls.lua
> 
> cmd = {DATA_PATH .. "/lspinstall/typescript/node_modules/.bin/typescript-language-server", "--stdio"},
> 
> which was added in [7367ca6](https://github.com/ChristianChiarulli/nvcode/commit/7367ca68b7c020b5839a1c84da9cf1f9627e82ae)

My path is right for tsserver.

**Comment by ChristianChiarulli** [comment]
This should be fixed after yesterday's livestream
