### ISSUE TITLE
Hey! I want to change the banner on the dashboard.

### ISSUE THREAD

**Issue by Samarth2005** [ChristianChiarulli/nvcode#164]
Hello Chris, 
You're doing awesome work on NVCode, and I love it. I have NVCode for heavyweight coding and IDE features, and vim as a minimal and fast editor. I'm a fan of this combo. 

I needed to change the banner that says NVCODE on the dashboard, just for customisation reasons, you know, but I can't seem to find the program that generates one as good as the default one. I usually use figlet for my banners, but the default NVCode banner just looks way better. 

So is it figlet with another font, or a different program altogether? 
Don't tell me it's custom made. I can't do it.

Anyway, Thanks, and keep up the good work.

**Comment by ChristianChiarulli** [comment]
Hey Samarth, I used this site to generate the logo: [link](https://textkool.com/en/ascii-art-generator?hl=default&vl=default&font=Red%20Phoenix&text=stacktraceguru)

**Comment by Samarth2005** [comment]
Thanks Chris! Means a lot. Keep up the good work!

**Comment by Zaedus** [comment]
I know this is a closed issue, but for those of you that are searching for the font that the current nvcode branch's logo has
![img-2021-05-24-222350](https://user-images.githubusercontent.com/42098470/119434918-c6dbfe80-bcde-11eb-9076-dcb7d236ffde.png)

It is specifically the 'ANSI Shadow' font [here](https://textkool.com/en/ascii-art-generator?hl=default&vl=default&font=ANSI%20Shadow&text=NVCODE)
