### ISSUE TITLE
Stuck during installation

### ISSUE THREAD

**Issue by en1tan** [ChristianChiarulli/nvcode#165]
Steps:
  `bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/nvim/master/utils/installer/install.sh)`

![image](https://user-images.githubusercontent.com/16443589/112558416-036aa700-8dcf-11eb-8a06-f90b11e44e3f.png)

It just gets stuck here, nothing else

**Comment by ChristianChiarulli** [comment]
hmm that's the +PackerInstall command complaining

**Comment by en1tan** [comment]
oh, so how do I make it work then

**Comment by ChristianChiarulli** [comment]
Script should be fixed for now, just run `:PackerInstall` after opening for the first time

**Comment by en1tan** [comment]
alright, then, that works
