### ISSUE TITLE
add go and c language support

### ISSUE THREAD

**Issue by wuhanhui** [ChristianChiarulli/nvcode#168]
These two languages are quite common now, please support them.

**Comment by ChristianChiarulli** [comment]
I never use them personally so I would it would probably be better if someone put a config in that understands the configurations better.

**Comment by jameswalmsley** [comment]
I've added #169 for C/C++ support.

**Comment by jameswalmsley** [comment]
I've added https://github.com/kabouzeid/nvim-lspinstall/pull/15 to support downloading clangd-11 with LspConfig.

**Comment by jameswalmsley** [comment]
Also PR for merging once that gets upstreamed:
https://github.com/ChristianChiarulli/nvcode/pull/171

**Comment by jameswalmsley** [comment]
See https://github.com/ChristianChiarulli/nvcode/pull/174 to fix support for the upstream LspInstall cpp support.
