### ISSUE TITLE
[Bug]: json.formatters get attached to js/ts/tsx/jsx lsp

### ISSUE THREAD

**Issue by OliverNChalk** [ChristianChiarulli/nvcode#1706]
### Problem description

It appears that json.formatters are getting attached to one of the LSPs that are active for .ts files. I have an older style config file but here you can see the diff between a working / broken config:

https://github.com/OliverNChalk/lvim/commit/4566080572b9a6cc4bba886d870bdce6c20b8854

Relevant extracts from the broken config are:
```lua
-- Languages
-- TypeScript
lvim.lang.typescript.linters = { { exe = "eslint_d" } }
lvim.lang.typescript.formatters = { { exe = "eslint_d" } }

lvim.lang.javascript.linters = lvim.lang.typescript.linters;
lvim.lang.javascript.formatters = lvim.lang.typescript.formatters;
lvim.lang.typescriptreact.linters = lvim.lang.typescript.linters;
lvim.lang.typescriptreact.formatters = lvim.lang.typescript.formatters;
lvim.lang.javascriptreact.linters = lvim.lang.typescript.linters;
lvim.lang.javascriptreact.formatters = lvim.lang.typescript.formatters;

-- JSON
lvim.lang.json.formatters = { { exe = 'prettierd' } } -- <-- results in prettierd being run on .ts files
```

Screenshot of LvimInfo when [config **doesn't**](https://github.com/OliverNChalk/lvim/blob/4566080572b9a6cc4bba886d870bdce6c20b8854/config.lua#L27) include JSON formatter:
![image](https://user-images.githubusercontent.com/11343499/136369750-66ffee6f-154e-4124-be9a-c0ad92892c29.png)

Screenshot of LvimInfo when [config **does**](https://github.com/OliverNChalk/lvim/blob/e33a39b39549052c80a36493c1c254d5837db169/config.lua#L27) include JSON formatter:
![image](https://user-images.githubusercontent.com/11343499/136369969-c68f099c-b14b-41ba-b16b-f82011a13668.png)

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

0ad60e90a9b0dd557df10f73bec344e88549a9d7

### Neovim version (>= 0.5)

NVIM v0.5.1

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
I tried `eslint_d` recently and it seems fine. Please let me know if you encounter any issues.
