### ISSUE TITLE
[Bug]: Empty lvim.autocommands.custom_groups table

### ISSUE THREAD

**Issue by argapost** [ChristianChiarulli/nvcode#1744]
### Problem description

After latest commit the lvim.autocommands.custom_groups is empty. 
I have a function in my .config/lvim that sets some custom autocommands:

```lua
local M = {}

M.config = function()
	-- Autocommands
	lvim.autocommands.custom_groups = {
		{ "FileType", "python", 'nnoremap <silent> ;t :lua require("user.rgrepl").open_repl()<CR>' },
		{ "FileType", "tex", "hi Conceal guibg=none ctermbg=none" },
		{ "FileType", "tex", "setlocal conceallevel=1" },
		{ "TermOpen", "*", "setlocal nonumber norelativenumber" },
	}
  print(vim.inspect(lvim.autocommands.custom_groups))
end

return M

```

When I open a file I can see the print that I have inside my function produces the correct table  but after that if I execute inside neovim 
`:lua print(vim.inspect(lvim.autocommands.custom_groups))` 
I get an empty (not nil) table.

This means that after my config the lvim.autocommands.custom_groups is set to "{}" somehow.

### LunarVim version

Rolling

### Neovim version (>= 0.5)

NVIM v0.6.0-dev

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by christopher-besch** [comment]
I can confirm the issue.

**Comment by argapost** [comment]
When I open lvim my config is loaded correctly so this function fills the `lvim.autocommands.custom_groups` with my autocommands but afterwards when the rest of the lunarvim config is loaded I guess, something resets the table to empty.

**Comment by kylo252** [comment]
I'm pretty sure it's the other way around for me, `custom_groups` is only getting updated after saving `config.lua`. I must've messed something up in the config-loader.
