### ISSUE TITLE
[Bug]: LSP is not activated when using Requirejs

### ISSUE THREAD

**Issue by angryheng** [ChristianChiarulli/nvcode#1748]
### Problem description

When I open a file that uses requirejs, LSP shows LS Inactive

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6.0

### Screenshots

<img width="1280" alt="bug" src="https://user-images.githubusercontent.com/28853495/136875611-ac142d49-13eb-4443-bbd8-aabe5cff6fe0.png">

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Do you have one of these files/folders in your project?   This is what the typescript server is looking for on startup.    "package.json", "tsconfig.json", "jsconfig.json", ".git"
