### ISSUE TITLE
[Bug]: Install with Command | Not working/bug?

### ISSUE THREAD

**Issue by ZoeLogiiK** [ChristianChiarulli/nvcode#1778]
### Problem description

Pop!_OS 21.04.
What I thought that would happen...

Install in one Command //Github//

Ask to install NodeJS Dependencies.
"yes"
*installs* or *error, run as sudo*
Continues installing.
========= V.S What actually happens ==========

![Screenshot from 2021-10-15 07-08-37](https://user-images.githubusercontent.com/53856528/137478140-de04ef23-3658-4907-9178-dc7d6ebbdb65.png)

Currently trying to understand a fix.

### LunarVim version

0.51

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+42-geece0735f

### Relevant log output

```shell
NVIM v0.6.0-dev+42-geece0735f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-55

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
===========================================================================
```

### Screenshots

![Screenshot from 2021-10-15 07-13-17](https://user-images.githubusercontent.com/53856528/137478601-521c5131-cccc-46c2-bbf5-c44d7b5aa374.png)
![Screenshot from 2021-10-15 07-13-45](https://user-images.githubusercontent.com/53856528/137478641-23cae40d-fa2f-4a51-bd42-ef403a82dd9e.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Can you please run the prerequisite steps listed here:  https://www.lunarvim.org/01-installing.html#prerequisites.  Specifically the step for resolving EACCES errors.
