### ISSUE TITLE
[Bug]: Lsp and which_key only start when i command :LvimUpdate  

### ISSUE THREAD

**Issue by lavixta** [ChristianChiarulli/nvcode#1803]
### Problem description

Hi i just updated to lvim recent version and i have a problem as i start new file it show up without lsp and other plugin like this
<img width="1437" alt="Screen Shot 2021-10-19 at 10 57 14 AM" src="https://user-images.githubusercontent.com/36840462/137841659-4bac1d53-42b1-403f-9290-db9c08c97908.png">
It is only when i command :LvimUpdate it show up Lsp and other thing 
<img width="1432" alt="Screen Shot 2021-10-19 at 10 58 22 AM" src="https://user-images.githubusercontent.com/36840462/137841752-c8add01c-9545-4e9b-96bc-12536a0ffe6c.png">
 When i close the file, start again appear and i have to do that again
 How can i fix this ? 

### LunarVim version

rolling 

### Neovim version (>= 0.5)

0.5.0 

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by lavixta** [comment]
> Can you also try `:LvimCacheReset` then run `:LvimUpdate`

I've tried it but after i close my file and start again it happend again, i am using MacOs Big Sur

**Comment by Ben-De** [comment]
Also experiencing this issue on Ubuntu 20.04 - unfortunately the same thing happens when I try the steps Rebuilt mentioned above.
