### ISSUE TITLE
[Bug]: colorscheme hides listchars

### ISSUE THREAD

**Issue by zalegrala** [ChristianChiarulli/nvcode#1812]
### Problem description

In porting over my old vim configs, I've now got the following.

```
vim.opt.list = true
vim.opt.listchars:append("tab:»·")
vim.opt.listchars:append("trail:·")
```
This seems to work well enough, but the characters are only visible when the line is highlighted due to the cursor.  

### LunarVim version

rolling HEAD

### Neovim version (>= 0.5)

v0.5.1

### Screenshots

![image](https://user-images.githubusercontent.com/88330524/138116024-aee7ab4a-e067-4754-b343-13fcb2e63f44.png)

Both lines highlighted have only whitespace.  You can see on the second line there, that the dots show up, though very faint.

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
can you check if #1817 fixes your issue or not?
