### ISSUE TITLE
Text hides behing the 'indentation field' when scrolling horizontally

### ISSUE THREAD

**Issue by weiss-d** [ChristianChiarulli/nvcode#187]
It feels rather confusing when indented text hides like shown on the gif when scrolling horizontally.
And when I press `C-_`, or `C-^` to go to the start of the line, cursor moves and also gets hidden.

![nvcode_bug](https://user-images.githubusercontent.com/62437174/112827563-2dee8580-9097-11eb-9c0d-c9e3e2871d00.gif)

**Comment by ChristianChiarulli** [comment]
My guess is this is indentblanklines fault, could you try disabling it?

**Comment by weiss-d** [comment]
How can I do this? Commenting out this line doesn't help.
![image](https://user-images.githubusercontent.com/62437174/112855167-3bb40300-90b7-11eb-9693-f89cae7ef4f5.png)

**Comment by ChristianChiarulli** [comment]
And if you continue to see this, I would recommend putting in an issue with indentblankline

**Comment by ChristianChiarulli** [comment]
Also remember to run `:PackerUpdate` after removing a plugin

**Comment by weiss-d** [comment]
Ok, after commenting out this line and running `:PackerUpdate` problem disappeared.
I will open an issue with the plugin.

**Comment by weiss-d** [comment]
UPD: yes, it is known bug an they're working on it.
