### ISSUE TITLE
VSCode (VSCodium) 'space' binding in keybindings.json prevents typing space anywhere except the editor.

### ISSUE THREAD

**Issue by weiss-d** [ChristianChiarulli/nvcode#217]
Any time I try to press `space` in a search box or settings etc. it will pop-up the `which-key` menu instead, until I delete the binding in `keybindings.json`:

![vscodium_error](https://user-images.githubusercontent.com/62437174/113389370-993a9f00-9398-11eb-82c7-1ce4a2647a79.gif)

My VSCodium data:
```
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-04-01T14:57:53.176Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.11-arch1-1
```

**Comment by ChristianChiarulli** [comment]
Anyone wanna tackle this? should be easy to add a !input or something in the keybindings.json.

**Comment by KarolusD** [comment]
Hi @weiss-d I am not sure if this is what you're looking for but it worked for me 😀
![Screenshot 2021-04-02 at 15 59 23](https://user-images.githubusercontent.com/35146988/113422129-7f1ab400-93cc-11eb-976a-c43ef935650f.png)

**Comment by KarolusD** [comment]
I believe you can also use this, which is even better because whickkey space shortcut will still work in the file explorer
![Screenshot 2021-04-02 at 16 09 37](https://user-images.githubusercontent.com/35146988/113422972-f3a22280-93cd-11eb-9c80-4a117b63d36b.png)
 @weiss-d

**Comment by weiss-d** [comment]
@KarolusD big thanks! Tried second one and it does the job.
