### ISSUE TITLE
treesitter error

### ISSUE THREAD

**Issue by argapost** [ChristianChiarulli/nvcode#218]
First of all, thank you for nvcode!

After merging the 7 last commits in nvcode and updating treesitter I get this error in every file that I open:

Error executing vim.schedule lua callback: ...ker/start/nvim-treesitter/lua/nvim-treesitter/indent.lua:77: attempt to index local 'prev_node' (a nil value)

Yesterday everything was working.

Any ideas?

**Comment by gitx-xx** [comment]
I just commented out the whole if statement at line 77 and now I'm able to work again.
`~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/lua/nvim-treesitter/indent.lua`

**Comment by Spuxy** [comment]
@gitx-xx yep it works pretty nice.

**Comment by argapost** [comment]
As a short-term solution it can work I guess, but it isn't very stable to change the treesitter code.
So is it a treesitter problem? or a problem from the nvcode configurations? I opened an issue in treesitter as well.

 https://github.com/nvim-treesitter/nvim-treesitter/issues/1131#issue-849089650

**Comment by hrqmonteiro** [comment]
I guess it's a treesitter error, i am not using Nvcode's config and got the error here as well, after i updated all of my plugins.

**Comment by ChristianChiarulli** [comment]
So the culprit is indentline?

**Comment by argapost** [comment]
Ok it was a problem of nvim-treesitter they fixed it so I can close this issue.
