### ISSUE TITLE
Telescope ignore node_modules folder.

### ISSUE THREAD

**Issue by joaop-oliveira1** [ChristianChiarulli/nvcode#220]
Hello whenever I activate Telescope it searches inside my node_modules folder, is there any place that I can configure it to ignore node_modules?

Thanks in advance!.

**Comment by BiserStoilov** [comment]
I set telescope - file_ignore_patterns - to nv-globals in my [PR Projects organizer #208](https://github.com/ChristianChiarulli/nvcode/pull/208)

**Comment by joaop-oliveira1** [comment]
is nv-globals a file I create local in my project? Or is It inside the nvcode config folder?

**Comment by BiserStoilov** [comment]
This is my changes - [link](https://github.com/ChristianChiarulli/nvcode/pull/208/commits/b2334367453928f7c0bf8dd76ab3cb83b0d17337)

Then you can set ignore_patterns in nv-settings.lua:
`O.telescope.ignore_patterns = {'node_modules/*', '.git/*'}`

**Comment by joaop-oliveira1** [comment]
Oh ok, understood now thanks for the help!!
