### ISSUE TITLE
Can't change fillchars

### ISSUE THREAD

**Issue by nikolasetiawan** [ChristianChiarulli/nvcode#2294]
### Problem description

Same question as in #2262,
I can't seem to change the fillchars in lvim config

I have tried lua way:
`vim.opt.fillchars = vim.opt.fillchars + "vert:\ "`
and vim way
`vim.cmd([[set fillchars=vert:\ ]])`

Setting it manually in neovim window works though:
`:set fillchars=vert:\ `

Are there other alternatives to change the fillchars in init.lua?

### LunarVim version

ff9ae8f

### Neovim version (>= 0.6.1)

0.6.1

### Operating system/version

mac OS Monterey

### Relevant log output

```shell
-
```

**Comment by nikolasetiawan** [comment]
Somehow I didn't have any luck with the proposed solution. But after some more digging, adding something like:
`vim.o.fillchars = "vert: ,eob:a"`
in the after/plugin folder works.
Not sure why it needs to be in the after folder though

**Comment by aserowy** [comment]
Just in case someone needs to set just one fillchars and gets navigated by search to this issue.

fillchars is an object in nvim. Thus, to override just a single entry, you can navigate to the specific one like every other property in lua. E.g.

```lua
vim.opt.fillchars.eob = "\\ "
```
