### ISSUE TITLE
Is there a way to uninstall it?

### ISSUE THREAD

**Issue by JosefLitos** [ChristianChiarulli/nvcode#232]
![obrazek](https://user-images.githubusercontent.com/54900518/113510670-33971000-955c-11eb-82b7-9405fe4a1d32.png)
Hello, so I just wanted to try your config out, but as it turns out, its like a virus, once you install it, you can't get rid of it. I removed the config. I even reinstalled neovim, but I still have the dashboard and other things that just completely destroy neovim usability as I can't even move around because it's so slow.
Steps to reproduce:
- install this using the given line of code
- run it with the :PackerInstall command
- maybe install an lsp server (I did json and html, but that should not make effect)
- remove the config

I wanted to go back, because I was unable to understand the config and pretty much anything, but even after removal, It does the tab identation with line, weird random key highliting and the tabs-like view.

**Comment by rebuilt** [comment]
When you say you removed the config do you mean you deleted the init.lua file in ~/.config/nvim.  Or did you delete the entire nvim folder folder and replace it with the folder you backed up?

**Comment by JosefLitos** [comment]
I removed the config folder, but I found the problem, you also have to delete ~/.local/share/nvim. That did the trick.

**Comment by trewjames** [comment]
For vim-plug users, remember to reinstall vim-plug after deleting ~/.local/share/nvim.

**Comment by barun108** [comment]
> For vim-plug users, remember to reinstall vim-plug after deleting ~/.local/share/nvim.

I was earlier using vim-plug , but I didn't need it with fresh install of LunarVim

yes , I added few more plugins, but only with packer
