### ISSUE TITLE
Indentation Problems

### ISSUE THREAD

**Issue by 23danielsuh** [ChristianChiarulli/nvcode#234]
Whenever I write code with some indentations, Neovim will just stop indenting it. For example, if I write the following code:

The line ( | ) represents where the indent line currently is. 

Behavior Now:
```
if(...) {

}else if(...) {
|
}
```
Expected Behavior: 
```
if(...) {

}else if(...) {
    |
}
```
This only happens occasionally, and I can't tell if it's an issue with Neovim nightly, or one of the configurations. However, when running `nvim -u NONE`, this problem goes away, making me think that it is an issue with one of the configurations. 

I have not changed the configuration whatsoever, so to replicate this behavior, you would just run the install script. 

EDIT: This happens only on if/else if/else code blocks in C++, but I have not tested it in other languages. Using curly braces for other parts of the code like for/while loops have been working perfectly fine.

Thank you!

**Comment by rebuilt** [comment]
I had to install a language server to get proper indentation in ruby.  What's the output of :LspInfo ?

**Comment by 23danielsuh** [comment]
I don't think it's a language server issue, I just tested the indentation on Java where I don't have a server installed, and the same issue happened. 

But here it is:
![ArcoLinux_2021-04-04_16-06-48](https://user-images.githubusercontent.com/63919918/113520257-c6857980-955f-11eb-83f9-4c45d446db8a.png)

**Comment by 23danielsuh** [comment]
I found the problem, it was treesitter that was messing up my indentations. I changed the treesitter config so that it was fully disabled, and then just used indentexpr to fix the issue.
