### ISSUE TITLE
How to install icons?

### ISSUE THREAD

**Issue by irishgreencitrus** [ChristianChiarulli/nvcode#235]
Installed this, love it btw it's working great apart from one thing.
Things that should be icons appear like this
![image](https://user-images.githubusercontent.com/43090499/113516213-e1141e80-9570-11eb-8dad-d03904904813.png)
Is there a package i need to install to get the correct icons?
I'm using manjaro btw if that helps

**Comment by rebuilt** [comment]
Do you have to use a nerd font installed? 
 https://www.nerdfonts.com/

**Comment by irishgreencitrus** [comment]
ah no, it's working now!!
