### ISSUE TITLE
Last few commits seems to have broken css file import in typescript project

### ISSUE THREAD

**Issue by kpritam** [ChristianChiarulli/nvcode#237]
CSS imports in typescript file were working fine few days back but now it seems to be broken.

Do you think, I am missing any settings?

![image](https://user-images.githubusercontent.com/17781757/113594345-33c70680-9655-11eb-8e68-70813a5be121.png)

**Comment by ChristianChiarulli** [comment]
may be a compe thing, not sure

**Comment by kpritam** [comment]
Last commit https://github.com/ChristianChiarulli/nvcode/pull/233 fixed the issue.

Closing this, Thanks!
