### ISSUE TITLE
module galaxyline not found

### ISSUE THREAD

**Issue by lukepunnett** [ChristianChiarulli/nvcode#240]
Recently fresh installed the latest Neovim (NVIM v0.5.0-dev+1226-g370469be2) on mac after uninstalling the previous version. 

I ran the script which ran fine without any issues and updated my zshrc file. I now get the following error: 

`/Users/lukepunnett/.cache/nvim/packer.nvim.log: Permission denied
E5113: Error while calling lua chunk: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:495: /Users/lukepunnett/.config/nvim/lua/nv-galaxyline/init.
lua:1: module 'galaxyline' not found:
        no field package.preload['galaxyline']
        no file './galaxyline.lua'
        no file '/Users/lukepunnett/neovim/.deps/usr/share/luajit-2.1.0-beta3/galaxyline.lua'
        no file '/usr/local/share/lua/5.1/galaxyline.lua'
        no file '/usr/local/share/lua/5.1/galaxyline/init.lua'
        no file '/Users/lukepunnett/neovim/.deps/usr/share/lua/5.1/galaxyline.lua'
        no file '/Users/lukepunnett/neovim/.deps/usr/share/lua/5.1/galaxyline/init.lua'
        no file './galaxyline.so'
        no file '/usr/local/lib/lua/5.1/galaxyline.so'
        no file '/Users/lukepunnett/neovim/.deps/usr/lib/lua/5.1/galaxyline.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
Error detected while processing /Users/lukepunnett/.local/share/nvim/site/pack/packer/start/nvim-lspconfig/plugin/lspconfig.vim:
line   18:
E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/lsp/log.lua:34: /Users/lukepunnett/.cache/nvim/lsp.log: Permission denied`

I have really searched to try and locate a solution with the above? Can anyone please assist? Please let me know if there is anything else I can provide that helps.

**Comment by kedare** [comment]
Same problem here

**Comment by OnunPereira** [comment]
Seems to be related with #236

**Comment by smikeblog** [comment]
try to :
1. delete /Users/lukepunnett/.cache/nvim  
2.  delete /Users/lukepunnett/.local/share/nvim/site/pack/packer
3. nvim
4. :PackerInstall
5. :qa!
6. nvim

**Comment by lukepunnett** [comment]
This solved the issue! Thanks @smikeblog

**Comment by smikeblog** [comment]
> This solved the issue! Thanks @smikeblog Any reason why this additional steps were required?

cashe && plugin/*.vim are for speed and are loaded first and if you change smth in config these files are not changed by Packer. Result is your error
