### ISSUE TITLE
Startup time is very slow

### ISSUE THREAD

**Issue by kpritam** [ChristianChiarulli/nvcode#246]
Recently I have observed that startup time is almost `1second`.
By running `nvim --startuptime ~/vim.log`, I can see loading colorscheme is taking around `300ms`

```
107.247  009.309  008.496: sourcing /.local/share/nvim/site/pack/packer/start/nvcode-color-schemes.vim/colors/lunar.vim
420.040  000.216  000.216: sourcing /.local/share/nvim/site/pack/packer/start/vim-which-key/autoload/which_key.vim
```

**Comment by ChristianChiarulli** [comment]
I have a couple ideas to speed things up, 
Remove unnecessary plugins: 

I'm thinking a more bare bones support for lsp, treesitter, colorscheme and a few other sane defaults like autopairs and completion should stay.

I'm not sure but I wonder if some of the lua based colorschemes are faster.

**Comment by kpritam** [comment]
It might not actually be `colorscheme` issue, when I followed few StackOverflow issues to profile vim startup, I got this results (stripped). That indicates, something to do with `filetype.vim` and `vim-polyglot`.


```
count total (s)   self (s)  script
    1  0.045202   0.003030  /usr/local/Cellar/neovim/HEAD-48e8057_2/share/nvim/runtime/syntax/syntax.vim
    1  0.002877   0.002498  /usr/local/Cellar/neovim/HEAD-48e8057_2/share/nvim/runtime/syntax/synload.vim
    4  0.001142   0.001142  /usr/local/Cellar/neovim/HEAD-48e8057_2/share/nvim/runtime/syntax/syncolor.vim
    2 151457.592053   151457.567693  /usr/local/Cellar/neovim/HEAD-48e8057_2/share/nvim/runtime/filetype.vim
    3  0.000091   0.000091  /Users/pritamkadam/.local/share/nvim/site/pack/packer/start/nvim-treesitter/ftdetect/query.vim
    3  0.000044   0.000044  /Users/pritamkadam/.local/share/nvim/site/pack/packer/start/vim-fugitive/ftdetect/fugitive.vim
    3 151457.591389   151457.568490  /Users/pritamkadam/.local/share/nvim/site/pack/packer/start/vim-polyglot/ftdetect/polyglot.vim
    
```

**Comment by kpritam** [comment]
OK, So after lot of trial and error, I figured out that culprit in my case is `nvim-tree`.
If I comment following line from `plugins.lua`, startup, save, update commands work super fast like before.
```
    use 'kyazdani42/nvim-tree.lua'
```

**Comment by kpritam** [comment]
Added comment here https://github.com/kyazdani42/nvim-tree.lua/issues/172#issuecomment-816005647

**Comment by kpritam** [comment]
Turns out issue was with my fish shell configuration. Fish had very long `PATH` configured. Closing this ticket.
