### ISSUE TITLE
WSL2 ubuntu: Error message when generating treesitter. 

### ISSUE THREAD

**Issue by dietrich** [ChristianChiarulli/nvcode#247]
Don't know if this is a issue with nvcode config or tree-sitter.
Issue:  With WSL2 ubuntu, it's looking for  "...tree-sitter-cli/tree-sitter", which doesn't exist because it's tree-sitter.exe (see attached pic)

quick fix: copy the tree-sitter.exe and rename removing  ".exe" extension.

![tree_sitter_wls2_error](https://user-images.githubusercontent.com/12489/114033315-c5479b80-9842-11eb-8616-f3a9d908dc19.png)

**Comment by chaeing** [comment]
First of all, this is not an issue with NVcode.

Second, the general rule for WSL2 is,
keep Windows stuff and WSL stuff separate.

Try installing it on your Ubuntu instance.

`
npm install -g tree-sitter-cli
`

**Comment by dietrich** [comment]
Yeah... thanks my error: thought I had installed tree-sitter-cli on my WLS2 Ubuntu instance... but apparently not.
