### ISSUE TITLE
NVIM crashing on opening a javascript file

### ISSUE THREAD

**Issue by en1tan** [ChristianChiarulli/nvcode#249]
I get the error `Client 2 quit with exit code 1 and signal 0` when trying to open a javascript file, this only happens on Javascript

**Comment by mjlbach** [comment]
FYI this is an error message I added that indicates a language server is crashing. See https://github.com/neovim/neovim/pull/14047

**Comment by en1tan** [comment]
alright then, I guess it is an issue of the Language Server then. thank you
