### ISSUE TITLE
Tagbar included in default setup

### ISSUE THREAD

**Issue by jasoncmcg** [ChristianChiarulli/nvcode#2792]
### Feature Description

As an alternative to a minimap, **tagbar** offers an excellent option as it includes a summary overview of the code with a bookmark link type of ability to jump to the relevant part of your code. 

LunarVim is awesome and is only missing this one aspect... that I can tell. (The aspect of a minimap type of option.)

I would guess that a response might be that it requires something external to be installed. However, the icons required me to install a font and then also configure konsole to use the font.

### Describe the alternatives you have considered

I thought there was maybe something with tree-sitter, but that appears to only be doing keyword highlighting...

**Comment by kobzar** [comment]
I think this is more personal moment. 
For my opinion, this plugin isn’t effective and need just beautiful screen. 
If file is not big - neoscroll is better choice. If file really big - i use marks. On both variants we dont spent time to left work. 
The same i can say about minimap. 
All this beauty’s  steal our working place and unfocusing our attention. 
So, thats why this plugin like others(colorizer, save work, surround e.t.c) is leave for user choice.
