### ISSUE TITLE
Unable to use lvim scp://server.123.123.123.123/~/.bashrc

### ISSUE THREAD

**Issue by palandovalex** [ChristianChiarulli/nvcode#2831]
### Problem description

vim and nvim support remote edit files via security copy(scp).

nvim scp://centos@123.123.123.123/~/.bashrc

It clones remove file to tmp dir, edit it, and after edit - it save it, an send changed file to remote server:

Due to ping, this is much more convenient than using the editor on the server itself.

When i tryed to use this with lvim - it does not worked as expected, but hapends strange error, and then it open empty file

### LunarVim version

rolling-48320e5

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"

### Steps to reproduce

gust try to use this standart nvim function with lvim:
https://gist.github.com/sloanlance/f481b7b8ffc0bfa3f46a1c942c7e7b78

### support info

i do not think that lviminfo, or lspinfo whould be helpful.

### Screenshots

Expected behavior of nvim:
![Снимок экрана от 2022-07-20 15-58-08](https://user-images.githubusercontent.com/75374436/180005297-8fc83cc9-968d-49b1-ae9f-b0086bd1c1a0.png)
![Снимок экрана от 2022-07-20 15-58-37](https://user-images.githubusercontent.com/75374436/180005298-97163392-2180-43ba-a452-0288cb5b63c1.png)

Behavior of lvim:
![Снимок экрана от 2022-07-20 15-55-45](https://user-images.githubusercontent.com/75374436/179991655-5fda0272-a94f-436d-a95f-e5c050bc75b0.png)

**Comment by rebuilt** [comment]
This is a complete guess but it looks like scp uses netrw under the hood to navigate to the right file on the remote filesystem.  Lunarvim uses nvimtree which overrides netrw.   When you launch `lvim .`  to view the local filesystem, it's using nvimtree not netrw.   You might be able to get the right behavior by setting this config options:

```
lvim.builtin.nvimtree.setup.disable_netrw = false
lvim.builtin.nvimtree.setup.hijack_netrw = false
```
