### ISSUE TITLE
LspInstall Terraform fails

### ISSUE THREAD

**Issue by soerenmartius** [ChristianChiarulli/nvcode#389]
When trying to run `:LspInstall terraform`, the installation of the language server fails with with exit code 1: 

```bash
.../site/pack/packer/opt/nvim-lspinstall/lua/lspinstall.lua:23: Could not install terraform language server!
```

I tried to install the server manually in `.local/share/nvim/lspinstall/terraform` also and tested it manually as well. However, if I run

```bash
:LspStart terraform
```

I get another error `E5108: Error executing lua ...im/site/pack/packer/opt/nvim-lspconfig/lua/lspconfig.lua:29: attempt to index a nil value`

**Comment by rebuilt** [comment]
Have you compiled neovim from source?  If not, follow the instructions to do that https://github.com/ChristianChiarulli/LunarVim#get-the-latest-version-of-neovim

**Comment by soerenmartius** [comment]
> Add this to terraform-ls.lua
> 
> ```lua
>      filetypes = { "tf", "terraform"},
> ```

didn't help unfortunately

**Comment by rebuilt** [comment]
Here are some other steps you can take:

- Make sure you're in a git directory
- Run  :PackerSync  to make sure you have the most updated configurations from lspconfig
- Open up terraform-ls.lua.  Make sure the cmd path matches what what exists in your system.
- Open up the expected path for terraform-ls and make sure it's there ~/.local/share/nvim/lspinstall/terraform/terraform-ls
- Make sure you're using a version of neovim you've compiled from source
- View the filetype in neovim and make sure it matches the lspconfig defaults:
```
    cmd = { "terraform-ls", "serve" }
    filetypes = { "terraform", "hcl" }
    root_dir = root_pattern(".terraform", ".git")
```
- Correct the default values if they don't match what's on your system.  
- Make sure you're restarting neovim after installing the language server
- Give the language server at least 5 seconds to attach to the buffer
- Use :LspInfo to make sure everything looks like the 'good' example https://github.com/ChristianChiarulli/LunarVim#example-configurations

**Comment by rebuilt** [comment]
I forgot to include the command for checking the filetype 
```
:set filetype?
```

**Comment by soerenmartius** [comment]
> I forgot to include the command for checking the filetype
> 
> ```
> :set filetype?
> ```

thanks!

Setting 

```bash
    filetypes = { "tf", "hcl", "terraform"},
```

in `terraform-ls.lua` helped - still, the language server can't be installed with `LspInstall terraform` but the standalone uild works. Thank You!

**Comment by rebuilt** [comment]
I think it works on some machines and not others.  It's hit and miss right now.  If you like, you can submit an issue upstream with the lspconfig project.  The LspInstall plugin seems to have done its job.  It installed the language server for you.  The problem is configuration(Lspconfig) which is going to be different on different architectures and operating systems.
