### ISSUE TITLE
ctrl+h and ctrl+l returns to normal mode in terminal mode

### ISSUE THREAD

**Issue by breneser** [ChristianChiarulli/nvcode#4192]
### Problem description

In version 1.3 of lunarvim ctrl+h and ctrl+l doesn't seem to get forwarded to the terminal, but instead returns to normal mode.

It seems to be working correctly with `lvim -u NORC`

I tested using without user configuration, issue still exists.

### LunarVim version

1.3

### Neovim version (>= 0.9.0)

0.90

### Terminal name

Alacritty and xfce4-terminal

### Operating system/version

manjaro linux

### Steps to reproduce

1. `lvim`
2. `:term`
3. `i for insert mode`
4. press `ctr+h` or `ctrl+l`

**Comment by kobzar** [comment]
In 1.3 release this default keys is deprecated
```lua
lvim.keys.normal_mode["<S-l>"] = ":BufferLineCycleNext<CR>"
lvim.keys.normal_mode["<S-h>"] = ":BufferLineCyclePrev<CR>"
```

**Comment by kobzar** [comment]
I show you just example before. 
So, this is your settings for this keys in terminal
```lua
--Disable Ctrl + h/l keys in terminal
lvim.keys.term_mode["<C-l>"] = false
lvim.keys.term_mode["<C-h>"] = false
```

So, you cand disable it or bind any action that you want to those combination like in sample
```lua
 lvim.keys.term_mode["<C-l>"] = ":BufferLineCycleNext<CR>"
 vim.keys.term_mode["<C-h>"] = "<cmd>SomeAction<cr>"
```

**Comment by cpea2506** [comment]
An explanation is those keymaps are remapped for changing between terminal windows. And when changing between windows, it will return to normal mode.

https://github.com/LunarVim/LunarVim/blob/ef3f25fd1d496c3822af9536d224270c48f12fff/lua/lvim/keymappings.lua#L71-L76

The solution above should work.

**Comment by breneser** [comment]
Thanks both, I am not sure why I couldn't see the mapping when I tried `map <C-L>`.

That solved the issue. Cheers!
