### ISSUE TITLE
characters not displayed

### ISSUE THREAD

**Issue by lukas3141** [ChristianChiarulli/nvcode#4574]
### Problem description

One file isnt shown properly. The file has the following content:
```
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" href="%sveltekit.assets%/favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		%sveltekit.head%
	</head>
	<body data-sveltekit-preload-data="hover">
		<div style="display: contents">%sveltekit.body%</div>
	</body>
</html>
```

I can properly edit and yank the content, but some characters are displayed as whitespace.

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

NVIM v0.9.5

### Terminal name

Alacritty

### Operating system/version

Asahi Linux Fedora 39

### Steps to reproduce

 1. create an svelte app `npm create svelte@latest my-app`
 2. open the file `src/app.html`. 

### Screenshots

![image](https://github.com/LunarVim/LunarVim/assets/22009283/b1eb823e-4391-4730-88dd-223902cc10c4)

**Comment by mateo-moon** [comment]
I don't know why exactly is that but the problem in the older version of [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) plugin. Here is [PR](https://github.com/LunarVim/LunarVim/pull/4575) with latest version. You can wait while this will be merged or just copy changes from PR to your local files to fix it. Don't forger to run ':LvimSyncCorePlugins' after saving changed files and running ':Lazy update'.

**Comment by lukas3141** [comment]
That's really nice. Thank you!
