### ISSUE TITLE
Failed to source `.local/share/lunarvim/site/pack/lazy/opt/nvim-treesitter/plugin/nvim-treesitter.lua`

### ISSUE THREAD

**Issue by PabloMartinMoreno** [ChristianChiarulli/nvcode#4578]
### Problem description

At startup I have an error regarding treesitter
![pic-full-240610-0225-31](https://github.com/LunarVim/LunarVim/assets/102924958/1fea9c92-619d-4bef-8b30-ddcb57a32465)

### LunarVim version

release-1.3/neovim-0.9-d1c1bace

### Neovim version (>= 0.9.1)

0.10.0

### Terminal name

st

### Operating system/version

Arch 6.9.3

**Comment by pgierz** [comment]
+1 I have this as well. In my case, Mac OS, nvim 0.10.0, Alacritty terminal.

**Comment by Walkability** [comment]
Did you guys figure out how to fix this?

**Comment by salimp2009** [comment]
if you are using lvim 1.3 you cannot use neovim 0.10.0
prefer lvim nightly  or lvim 1.4 with neovim 0.9.5 (some people also reported lvim 1.4 is OK with neovim 0.10.0
this is related to you are on wrong version of lvim for your neovim version.
lvim 1.3 -> neovim 0.9.+
lvim 1.4 -> neovim 0.9.5+
lvim nighly (master) -> 0.10
As far as I know

**Comment by salimp2009** [comment]
> Did you guys figure out how to fix this?

if

> Did you guys figure out how to fix this?

if you are using lvim 1.3 you cannot use neovim 0.10.0
lvim 1.3 -> neovim 0.9.+
lvim 1.4 -> neovim 0.9.5+
lvim nighly (master) -> 0.10

**Comment by salimp2009** [comment]
This iissue can be closed. User is using wrong version of neovim with wrong version of lvim
@PabloMartinMoreno if you want to use neovim 0.10.0 prefer lvim 1.4 and lvim nightly
