### ISSUE TITLE
error: unknown flag `u'

### ISSUE THREAD

**Issue by adrianatrevinoe** [ChristianChiarulli/nvcode#4579]
### Problem description

Hello! When installing lvim I get this:
![image](https://github.com/LunarVim/LunarVim/assets/70771428/641cf959-6de6-4db8-af8d-2db906e8d328)
Here is what i get from ./local/bin/lvim
![image](https://github.com/LunarVim/LunarVim/assets/70771428/dcdc2391-bc75-4a96-8408-db1eeb3c50ff)

### LunarVim version

-

### Neovim version (>= 0.9.1)

0.10

### Terminal name

Termianl

### Operating system/version

ubuntu 20.04

**Comment by adrianatrevinoe** [comment]
![image](https://github.com/LunarVim/LunarVim/assets/70771428/087f51a4-d653-4bcb-bbbb-77ac3fcc6428)

**Comment by ippatev** [comment]
&gt; [Jun 11, 2024](#event-13118144097) Hi, have you solved this problem?
