### ISSUE TITLE
Integration for Rust "rustoceanivm" plugin that replaced "rust-tools". 

### ISSUE THREAD

**Issue by Firwanaa** [ChristianChiarulli/nvcode#4581]
### Feature Description

**`TL;DR`**  *I'm not able to get `rustaceanvim` rust plugin to work properly with LunarVim.*

#### The request: 

This Rust plugin ['simrat39/rust-tools.nvim' ](https://github.com/simrat39/rust-tools.nvim?tab=readme-ov-file) is archived now, and the plugin author asking people to switch to ['mrcjkb/rustaceanvim'](https://github.com/mrcjkb/rustaceanvim). Both plugins provide non-standard additional features for rust-analyzers and I couldn't find any documentations how to set it up in LunarVim, except for 2 years old discussion for the archived plugin. The `rustaceanvim` plugin conflicts with `rust-analyzer`, as the plugin author mentions "*This plugin automatically configures the rust-analyzer builtin LSP client and integrates with other Rust tools*" and also adding the following warning "*Do not call the [nvim-lspconfig.rust_analyzer](https://github.com/neovim/nvim-lspconfig) setup or set up the LSP client for rust-analyzer manually, as doing so may cause conflicts.*". 

### Describe the alternatives you have considered

Rust analyzer is still available and actually provides enough features, however I would like also to see more documentations specific for LunarVim. 

### Support information

Closed issue I found related to the archived plugin:

https://github.com/LunarVim/LunarVim/issues/2894

**Comment by vaporif** [comment]
Just follow guide https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#inbox_tray-installation

```
lvim.plugins = {
  {
    'mrcjkb/rustaceanvim',
    version = '^4', -- Recommended
    lazy = false, -- This plugin is already lazy
  },
...
}
```

make sure no mention of `rust-tools` in inside your config
you will face some minor bugs (i.e. [issue faced by me](https://github.com/rust-lang/rust-analyzer/issues/17219)) if you'd still use rust-tools with current (1.79.0 atm) rust so transition to `rustaceanvim` is recommended

Also as a minimal setup add
```
lvim.builtin.which_key.mappings["C"] = {
  name = "Rust",
  r = { "<cmd>RustLsp runnables<Cr>", "Runnables" },
  t = { "<cmd>RustLsp testables<Cr>", "Testables" },
  e = { "<cmd>RustLsp expandMacro<Cr>", "Macro Expand" },
  h = { "<cmd>RustLsp hover actions<Cr>", "Hover" },
  p = { "<cmd>RustLsp rebuildProcMacros<Cr>", "Rebuild Macros" },
  g = { "<cmd>RustLsp codeAction<Cr>", "Code Action" },
  x = { "<cmd>RustLsp explainError<Cr>", "Explain Error" },
  d = { "<cmd>RustLsp renderDiagnostic<Cr>", "Diagnostic" },
  c = { "<cmd>RustLsp flyCheck<Cr>", "Check" },
}

```

I might update rust specific config after I'm done with mine
