### ISSUE TITLE
`format_on_save` not working for python files

### ISSUE THREAD

**Issue by Noxdor** [ChristianChiarulli/nvcode#4592]
### Problem description

1. Install `black` or `ruff`
2. In `config.lua` set:
```lua
lvim.format_on_save.enabled = true

local formatters = require("lvim.lsp.null-ls.formatters")

formatters.setup({
	{ name = "ruff" },
	{ name = "prettierd" },
	{ name = "rustfmt" },
	{ name = "stylua" },
})

local linters = require("lvim.lsp.null-ls.linters")

linters.setup({
	{
		name = "eslint_d",
		condition = function(utils)
			return utils.root_has_file({ ".eslintrc.json", ".eslintrc.js", ".eslintrc.cjs" })
		end,
	},
})
```
3. save a Python file -> No formatting. Run `:lua vim.lsp.buf.format()` -> File is being formatted

### LunarVim version

release-1.4/neovim-0.9-d15c8d77

### Neovim version (>= 0.9.1)

v0.10.0

### Terminal name

Alacritty

### Operating system/version

Arch Linux (Garuda Linux)

### Steps to reproduce

Config provided above.

I tested it with `black` as well to make sure `ruff` isn't the issue. Same situation.

**Comment by fcpoloia** [comment]
You need to specify command to be executed in `formatters.setup`. Here's my config as an example
```lua
lvim.format_on_save=true
local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup{
  {command="black",filetypes={"python"}}
}
```
It works for me anyway

**Comment by Noxdor** [comment]
Unfortunately, neither setting `command` nor `filetypes` fixes this issue for me. I really don't get it because formatting works fine with any other language and it does work with Python when calling `:lua vim.lsp.buf.format()`.

**Comment by fcpoloia** [comment]
the issue might be `lvim.format_on_save.enabled = true`, I have `lvim.format_on_save=true` *without* `.enabled` and when I try to add it lua throws a warning. The formatter still works but try removing that part and see if anything changes

The warning:
```lua
[WARN ] lvim: "Invalid configuration: /home/fcpolonia/.config/lvim/config.lua:33: attempt to index field 'format_on_save' (a b
oolean value)" file="[C]", line=-1
```

**Comment by Noxdor** [comment]
I already testet that but it is not the cause of this issue, it is also documented in this way in the docs: https://www.lunarvim.org/docs/configuration/language-features/linting-and-formatting#formatting-on-save

**Comment by pshort** [comment]
I have this issue as well. I want to use ruff as a formatter and linter, and pyright as the lsp. Im migrating off of flake8 and black, as the 2 fight over some things.

``` lua
local formatters = require "lvim.lsp.null-ls.formatters"
formatters.setup({
  { command = "ruff",     filetypes = { "python" } },
  { command = "prettier", filetypes = { "json" } },
})
lvim.format_on_save.enabled = true
local linters = require "lvim.lsp.null-ls.linters"
linters.setup { { command = "ruff", filetypes = { "python" } } }
```

This is my config. I have ruff installed via :Mason, I also have ruff package via poetry and run it as part of my git hooks.
I want formatting to happen when I save a file, but nothing happens. I've also tried running:

``` bash
:lua vim.lsp.buf.format()
``` 
but it doesnt format. 

I've also tried
``` bash
!ruff format
``` 
but it doenst format anything that way either. However from my terminal, ruff format, fixes the file I am testing on.

**Comment by pshort** [comment]
Ahh, so after some digging I see that ruff is not actually in the list of supported linters or formatters. I can see in the lvim docs a section about how to setup unsupported tooling - I guess perhaps ruff falls under that umbrella, although it is odd that I can install it from :Mason...

[Registering Custom Linters adn Formatters](https://www.lunarvim.org/docs/configuration/language-features/linting-and-formatting#registering-custom-lintersformatters)
