### ISSUE TITLE
lunarvim php buffer with Heredoc

### ISSUE THREAD

**Issue by AndreiLosev** [ChristianChiarulli/nvcode#4597]
### Problem description

Lunarvim closes if you open a php buffer containing Heredoc

### LunarVim version

release-1.4/neovim-0.9-d15c8d7-dirty

### Neovim version (>= 0.9.1)

0.9.5

### Operating system/version

Linux fedora

### Affected language servers

php (phpactor, psalm, intelephense)

### Steps to reproduce

1. mkdir lvim-php-problem
2. composer init
3. lvim index.php
4. insert:
`<?php

$x = <<<QWE
QWE`

### Actual behavior

Lunarvim is closing

### Expected behavior

Lunarvim works

### support info

**lvimInfo:**
Active client(s)
* name:                      phpactor
* id:                        1
* supported filetype(s):     php
* attached buffers:          6
* root_dir pattern:          6
* capabilities:              selectionRangeProvider | definitionProvider     | documentSymbolProvider
                             hoverProvider          | implementationProvider | workspaceSymbolProvider
                             referencesProvider     | typeDefinitionProvider | documentHighlightProvider

Formatters info
* Active: 
* Supported: [phpcbf, phpcsfixer, pint]

Linters info
* Active: 
* Supported: [php, phpcs, phpmd, phpstan, psalm]

**LspInfo:**

 Language client log: /home/andrei/.local/state/lvim/lsp.log
 Detected filetype:   php
 
 1 client(s) attached to this buffer: 
 
 Client: phpactor (id: 1, bufnr: [6])
 	filetypes:       php
 	autostart:       true
 	root directory:  /home/andrei/documents/spurIt/bugs
 	cmd:             /home/andrei/.local/share/lvim/mason/bin/phpactor language-server
 
 Other clients that match the filetype: php
 
 Config: psalm
 	filetypes:         php
 	root directory:    Not found.
 	cmd:               /home/andrei/.local/share/lvim/mason/bin/psalm-language-server
 	cmd is executable: true
 	autostart:         true

 Configured servers list: phpactor, psalm, tailwindcss

**Comment by belal-i** [comment]
I am also experiencing this issue. Is there a workaround to this? heredoc is a very useful PHP feature, and I have some code that uses it quite a bit. It is quite frustrating if Lunarvim crashes every time I accidentally open a file that contains that syntax. Actually, it's a little dangerous even, because it seems like unsaved buffers are lost if it crashes.

**Comment by chas-mafli** [comment]
I'm also experiencing this... I just can't use lunarvim for some files, it's very frustrating 😩
