### ISSUE TITLE
LunarVim seems to freeze when trying to delete text in config.lua

### ISSUE THREAD

**Issue by aethnae** [ChristianChiarulli/nvcode#4622]
### Problem description

Whenever i try to delete something in **normal mode** in my config.lua, it seems like Neovim freezes. There is a white bar blinking below the currently selected character, but besides that, nothing happens. I tried several keys, but nothing seems to return back to normal. This only happens when I delete characters in the config.lua file, for all my other files it works just as expected. Deleting in insert mode still works in the config file.

### LunarVim version

release-1.4

### Neovim version (>= 0.9.1)

neovim-0.9-d15c8d77

### Terminal name

iTerm2

### Operating system/version

macOS 15.0.1

### Steps to reproduce

1. open lvim with the `lvim` command
2. press `c` to access your `config.lua` file
3. press `dd` anywhere on a line with text.
4. You should by now see a white line below the character you're currently on, unable to do anything else than quit iTerm2

### Screenshots

![CleanShot 2024-11-12 at 12 38 03](https://github.com/user-attachments/assets/4e0d60dd-f464-4dc8-8ef5-551869ca20b8)

The white line that is blinking is currently below the second `c` in "conceallevel".

**Comment by ali-dc** [comment]
I'm also seeing this on neovim v0.10.2, and macos 14.7.1, using Alacritty as my terminal. Not just in `config.lua`, also in some Python files (although not all the time)

**Comment by nsmith-laudio** [comment]
Can confirm, came here to say I'm seeing the same. vim freezes edit TypeScript files and has high CPU. The only thing I can do is manually kill the process.

**Comment by nathasm** [comment]
Can confirm. vim freezes when editing TypeScript files and has high CPU. The only option is to `kill -9`. This is OSX 15.0.1 + iTerm2 using a default lunarvim config.

**Comment by nathasm** [comment]
I suspect it's outside the scope of LunarVim as neovim users are reporting similar issues.

If the this issue proves to be true: https://github.com/neovim/neovim/issues/31163 then it looks like it's related to tree sitter: https://github.com/tree-sitter/tree-sitter/issues/3930

**Comment by aethnae** [comment]
@nathasm @ali-chapman it indeed does, the homebrew formula (if you're on macOS) has already been reverted to the previous version, uninstalling tree-sitter with `brew uninstall --ignore-dependencies tree-sitter` and then reinstalling it fixes the issue for me.

**Comment by carlocab** [comment]
> the homebrew formula (if you're on macOS) has already been reverted to the previous version

To avoid misleading anyone:
- the fix was backported to the latest version of `tree-sitter` (Homebrew almost never reverts version updates)
- Homebrew works on Linux too.

> uninstalling tree-sitter with `brew uninstall --ignore-dependencies tree-sitter` and then reinstalling it fixes the issue for me.

It may be simpler to
```
brew update && brew reinstall tree-sitter
```
to avoid having to uninstall tree-sitter.

**Comment by TheBearodactyl** [comment]
i'm now having the same issue but it happens with `configuration.nix` instead
