### ISSUE TITLE
E492: Not an editor command: NvimTreeToggle

### ISSUE THREAD

**Issue by ralph32** [ChristianChiarulli/nvcode#4626]
### Problem description

I'm trying to remap keys for nvim-tree (j and k keys to move up and down in file tree). This config works in nvim-tree but when I put it in config.lua for LunarVim I get "E492: Not an editor command: NvimTreeToggle"

config.lua
```lua
local function setup_nvim_tree()
    require("nvim-tree").setup({
      on_attach = function(bufnr)
        -- Default mappings
        local api = require('nvim-tree.api')
        
        -- custom key mappings
        local opts = { buffer = bufnr, noremap = true }
        vim.keymap.set({'n', 'x'}, 'e', 'k', opts)
        vim.keymap.set({'n', 'x'}, 'n', 'j', opts)
      end
    })
  end
  
lvim.config.nvimtree = setup_nvim_tree()
```

### LunarVim version

release-1.4/neovim-0.9-d15c8d7

### Neovim version (>= 0.9.1)

NVIM v0.9.5, Build type: Release, LuaJIT 2.1.1703358377

### Terminal name

iTerm2

### Operating system/version

macOS 15.1.1

**Comment by juicy-g** [comment]
I was able to achieve your remaps with this code:
```lua
lvim.builtin.nvimtree.setup.on_attach = function(bufnr)
  -- Default mappings
  local api = require "nvim-tree.api"

  -- custom key mappings
  local opts = { buffer = bufnr, noremap = true }
  vim.keymap.set({ "n", "x" }, "e", "k", opts)
  vim.keymap.set({ "n", "x" }, "n", "j", opts)
end
```
However, Lunarvim also has a custom `on_attach` function called in the setup so you will lose some of its [unique mappings](https://github.com/LunarVim/LunarVim/blob/85ccca97acfea9a465e354e18bb2f6109ba417f8/lua/lvim/core/nvimtree.lua#L302). To fix that I would copy the Lunarvim `on_attach` with your changed mappings at the bottom :
```lua
lvim.builtin.nvimtree.setup.on_attach = function(bufnr)
  local api = require "nvim-tree.api"

  local function telescope_find_files(_)
    require("lvim.core.nvimtree").start_telescope "find_files"
  end

  local function telescope_live_grep(_)
    require("lvim.core.nvimtree").start_telescope "live_grep"
  end

  local function opts(desc)
    return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
  end

  api.config.mappings.default_on_attach(bufnr)

  local useful_keys = {
    ["l"] = { api.node.open.edit, opts "Open" },
    ["o"] = { api.node.open.edit, opts "Open" },
    ["<CR>"] = { api.node.open.edit, opts "Open" },
    ["v"] = { api.node.open.vertical, opts "Open: Vertical Split" },
    ["h"] = { api.node.navigate.parent_close, opts "Close Directory" },
    ["C"] = { api.tree.change_root_to_node, opts "CD" },
    ["gtg"] = { telescope_live_grep, opts "Telescope Live Grep" },
    ["gtf"] = { telescope_find_files, opts "Telescope Find File" },
  }

  require("lvim.keymappings").load_mode("n", useful_keys)

  local other_keys = {
    ["e"] = { api.node.navigate.sibling.prev, opts "Up" },
    ["n"] = { api.node.navigate.sibling.next, opts "Down" },
  }

  require("lvim.keymappings").load_mode({ "n", "x" }, other_keys)
end
```

**Comment by juicy-g** [comment]
Just to add to my previous comment. I don't know what the actual cause of the issue is. I suspect its `setup` getting called twice, but I can't confirm.

**Comment by ralph32** [comment]
wow. thanks!

**Comment by ralph32** [comment]
@juicy-g it works, but one thing i noticed is when using the remapped keys for j and k, it doesnt let me navigate outside of the directory. i.e. when on the last item in the directory and i click n key (j key for down) it shoots me to the top of the directory whereas before it allowed me to navigate outside of the directory. any idea why this is the case?

**Comment by juicy-g** [comment]
My bad. I never remapped key in nvim-tree before. I didn't test it too much either. You can just remap `j` and `k` rather than `api.node.navigate.sibling.prev` and `next`. I ommitted the lines above this snippet since they are unchanged: 
```lua
require("lvim.keymappings").load_mode("n", useful_keys)

local other_keys = {
  ["e"] = { "k", opts "Up" },
  ["n"] = { "j", opts "Down" },
}

require("lvim.keymappings").load_mode({ "n", "x" }, other_keys)
```
