### ISSUE TITLE
Don't understand this <TAB>: completion line

### ISSUE THREAD

**Issue by unknowledgeable** [ChristianChiarulli/nvcode#49]
Hi, I'm going through your tutorials and copying bits from here and there and came across this line in your mappings file:

```
" <TAB>: completion.
inoremap <silent> <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
```
I see it's something to do with tab-completion for something or other but can't figure out what it means or why it's necessary.
It looks to me like you're mapping <TAB> to <C-n> to scroll down the list of completions but if I comment this line out I seem to get the same behaviour. I've had a google and found [this](https://vim.fandom.com/wiki/Improve_completion_popup_menu) but I still think I'm missing something.

Would you mind shedding some light?

Cheers

**Comment by ChristianChiarulli** [comment]
This has been removed, orignally it was just to trigger the pum. I've since come to realize I'm not a big fan of this mapping.
